### ISSUE TITLE
Testing: Data Cleaning

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/DataCleaning#4]
This module is for low-level auditing and cleaning of resource metadata. Test it against Omeka S v2.

Here's typical workflow, from beginning to end, for a user who wants to audit the titles of items in a specific item set:

- Install the Data Cleaning module (Omeka S 2.x)
- Click on the "Data Cleaning" link (under "Modules")
- Click on "Prepare new audit" button (top right)
- Select criteria (expand arrows for info):
    - Resource type: "Item"
    - Resource query: `item_set_id[]=1234`
    - Audit column: "value"
    - Property: "Dublin Core: Title"
    - Data type: "Text"
- Ignore the "Advanced" section
- Click "Submit" (top right)
- Audit the "From: value" column for potential corrections or removals
- Make corrections by entering the correct text into the "To: value" column
- Make removals by checking the "Remove" checkbox
- Click "Submit" (top right)
- Click to confirm the submission
- Refresh the "Past audits" page until the job is marked as "Completed"
- Check the items to see if the values were corrected and removed.

There are quite a few more possible workflows, which should become more obvious as you use the interface. For example, you could change the audit column, the property, and the data type (the "targets"). You can validate against the set data type. Since there's a real possibility of permanent destruction of data, we'll need to outline the caveats in documentation.

**Comment by mebrett** [comment]
It seems to work as far as I can tell. It's a bit hard to test with random datasets. 
I'm going to keep working on it to see what I can do. Is it meant to work with modules like Numeric Data Types? And I'm assuming one can't use this to convert from one data type to another (from text to interval, ex)

**Comment by jimsafley** [comment]
This is good. I'm hoping this issue will start an extended conversation about the module's features. There are far too many moving parts to describe everything with one comment.

I designed this module for administrative power users to modify their data at a low level. By "low level" I mean there are very few layers between what is stored in the database and what the user sees. So, when auditing the "Numeric: Timestamp" data type, the user will see "1976-08-24" instead of "August 24, 1976"; and when setting the target data type to "Numeric: Timestamp", the user must use a plain textarea instead of the year/month/day/etc. select menus that are rendered on the resource form.

To answer your question: you _can_ use this to convert from one data type to another. That's one of the key features of the module. However, as hinted at above, the user must have prior knowledge on how to format the value. The module does not provide an interface to ensure a valid format, like Omeka does on the item form. (It does, however, provide a "Validate" button to check validity.) So, when converting from text to timestamp, the module will display "August 24, 1976", and the user must write "1976-08-24" by hand in the textarea. This is what "low level" looks like.

For documentation we should probably provide some "recipes" of common data type conversions. One helpful recipe would be "Text" to "URI", where a user has many URLs saved as plain text that they want to convert to linked URLs. It would look something like this:

- Audit column: value
- Property: (any property)
- Data type: Text
- Target audit column: uri
- Property: (any property)
- Data type: URI

By the way, users can also convert from one property to another. So be sure to test that also.

**Comment by mebrett** [comment]
I am going to need your help when writing the documentation for this (when we get there).

I will try and pull together some data with plaintext urls (unless someone has some in an Omeka 2 instance I can siphon). Working on doing a datatype conversion but I need to do more research on formats. 

One feature which might be helpful as we move forward is the ability to duplicate the basic parts of an audit  - or at least the query. The use case being that you have data, you clean it, you add more items, you want to do the same kind of cleaning again.

**Comment by sharonmleon** [comment]
In beginning the audit process, I screwed up and didn't fill one of the required elements on the form. I got the alert that I missed something, but the reload of the form totally reset, so I lost my query string. Would be better if the completed elements of the form were saved.

**Comment by sharonmleon** [comment]
So, I think I was successful in my testing scenario, though it took me a while to figure out what I was doing. I have universe of people with a property foaf:gender. That property should be filled with a custom vocabulary. For 12 of my 62 people, it was a text value. I updated them to the controlled vocab data type. Now an audit for text types for that property returns no results, suggesting success.

Next, I cleared the values out of the gender field for 50 of those people using the batch edit. I was able to find them in the data cleaning module with the search string, but because there were no values for that property there was no way to audit the "unique values." I was going to fill them with a selection from the controlled vocabulary. So, I guess that is a fail?

Next, I decided to update the dcterms:source fields, which are URIs, for events. There is lots of cruft here. My issue is clearly user error: I fixed one unique value and hit submit, loosing the audit of the remaining screwed up stuff. So, my question is if it is possible to not only have access to the record of past audits, there is away to hold prepared audit akin to saving a search? That might be too much at this stage.

Finally, I tried to figure out how to locate all of the people in a set who have Item values for Relationship:SpouseOf so that I could switch those item values to the property Relationship:LifePartnerOf. I'm not sure if I formed the query wrong or if something isn't working correctly.  
![propertychange](https://user-images.githubusercontent.com/741480/90645615-2a8f4380-e204-11ea-998c-428c01438218.png)

Generally, I'm fairly sure that we are going to need fairly careful documentation here and a lot of in-interface helper text for people to use this very powerful tool.

**Comment by jimsafley** [comment]
Thanks for taking the time to test this.

> In beginning the audit process, I screwed up and didn't fill one of the required elements on the form. I got the alert that I missed something, but the reload of the form totally reset, so I lost my query string. Would be better if the completed elements of the form were saved.

Ideally, we'd rely on client-side validation, but I can't set the "required" attribute on select elements that use [Chosen](https://harvesthq.github.io/chosen/) because it would raise a silent "invalid form control is not focusable" error (Chosen hides default select elements). Keeping the workflow as-is, we have two options:

a) Keep Chosen, rely on server-side validation, lose form state when invalid (current behavior)
b) Remove Chosen, rely on client-side validation, retain form state when invalid (by removing Chosen, the select elements lose their integrated filter)

> Next, I cleared the values out of the gender field for 50 of those people using the batch edit. I was able to find them in the data cleaning module with the search string, but because there were no values for that property there was no way to audit the "unique values." I was going to fill them with a selection from the controlled vocabulary. So, I guess that is a fail?

What you're trying to do is beyond the scope of the module. It's made exclusively for data correction and removal, not data entry.

> Next, I decided to update the dcterms:source fields, which are URIs, for events. There is lots of cruft here. My issue is clearly user error: I fixed one unique value and hit submit, loosing the audit of the remaining screwed up stuff. So, my question is if it is possible to not only have access to the record of past audits, there is away to hold prepared audit akin to saving a search? That might be too much at this stage.

Saving prepared audits is definitely an ambitious feature request. Something for another time?

> Finally, I tried to figure out how to locate all of the people in a set who have Item values for Relationship:SpouseOf so that I could switch those item values to the property Relationship:LifePartnerOf. I'm not sure if I formed the query wrong or if something isn't working correctly.

I'm guessing that you need to change the "Audit column" and "Target audit column" from "value" to "value_resource_id". The distinction is esoteric, I admit, and certainly something we need to document clearly.

I made this module with power users in mind, so the learning curve will be steeper than the typical module. In fact, we should actively discourage casual users from using it at all, possibly by stating "We highly recommend that you backup your database prior to auditing your data" in big, bold letters at the top of the manual.

**Comment by sharonmleon** [comment]
Thanks for this, Jim. I appreciate your notes. I agree that saving prepared audits is for another stage, but I wanted to note it. As for the two options on the form validation, do you have a strong preference for one over the other? I admit, once I made the mistake I was alert to the loss of the inputs, so I was more careful with the requirements.

Your suspicion on the the final fail is correct. I'm pretty sure documentation would have headed off that one.

**Comment by sharonmleon** [comment]
As for the data entry problem, I figured out a way to do it, which was to use the batch edit in the Items area to add the value to the property as text, and then use the this module to change those value from text to the controlled vocabulary data type.

**Comment by jimsafley** [comment]
> As for the two options on the form validation, do you have a strong preference for one over the other?

I don't have a strong preference. Really, which option has the most benefit: client-side validation or option filtering? Without client-side validation, we get the current behavior of losing configuration if the form is invalid. Without option filtering, users will not be able to filter the lists of properties and data types (the lists can be very long).

**Comment by sharonmleon** [comment]
I actually think that the filtering is essential.

**Comment by katknow** [comment]
I followed the instructions above using the title as the property I'm auditing. I noticed that if I edit the Dublin Core title through the module, the change appears if you click through to the metadata but its title in the private and public items page remains the same at the top of the page. Sorry if that's a bit incoherent, this is what I'm looking at (old title was "I Have a Dream" Inscription, changed it to just be "I Have a Dream" as reflected in the metadata): 

<img width="807" alt="Screen Shot 2021-08-05 at 8 20 19 PM" src="https://user-images.githubusercontent.com/84726696/128437500-bdf2d5d1-9db6-44dd-a65d-30122e619422.png">

Another example, in which I made "lockkeeper" two words:

<img width="1138" alt="Screen Shot 2021-08-05 at 8 36 12 PM" src="https://user-images.githubusercontent.com/84726696/128438413-190d6db9-1d2d-4944-a10c-3f002da51f1c.png">

<img width="800" alt="Screen Shot 2021-08-05 at 8 23 48 PM" src="https://user-images.githubusercontent.com/84726696/128437740-08096e1e-a6e0-429b-9801-1725545976a5.png">

However, if you go to edit the metadata, you can click inside the title field then re-save and then it will reflect the changes at the top of the page as well, but I'm guessing the module is supposed to circumvent that since the fields are linked if you do it on the individual item page.

<img width="799" alt="Screen Shot 2021-08-05 at 8 34 37 PM" src="https://user-images.githubusercontent.com/84726696/128438311-45f63257-cd35-404e-9c13-485422041938.png">

<img width="814" alt="Screen Shot 2021-08-05 at 8 42 43 PM" src="https://user-images.githubusercontent.com/84726696/128438825-ec5c4501-787f-496b-b5c5-83a65af49c8e.png">

Please let me know if I can try to explain that more clearly! Tried in different browsers, cleared cache, hard refreshed, etc. to same result each time.

**Comment by sharonmleon** [comment]
So, you're saying that the item title updates, but the listing on the browse page (table of items) does not?

Have you hard refreshed at each screen? (Item, item edit, Items browse)

**Comment by katknow** [comment]
I tried hard refreshing on the module page, the browse page, and the individual item and its edit page to no success. The item title updates only in the metadata, so the heading at the top of the screen above the tabs for values/media/item sets/etc. on the individual item page also doesn't change unless you manually re-save.

<img width="807" alt="Screen Shot 2021-08-05 at 8 20 19 PM" src="https://user-images.githubusercontent.com/84726696/128442268-c9c9fde7-1a6a-404f-80e4-f54d6e452525.png">

**Comment by jimsafley** [comment]
@katknow It makes total sense. Thanks for being so thorough. This happens because the module operates at such a low level, it circumvents the normal code path that handles titles. I still consider this to be a bug and will need to update the display title when a user modifies the `dcterms:title`.

**Comment by sharonmleon** [comment]
Thanks @katknow. Now I get it :)

**Comment by katknow** [comment]
Been playing around with this more today, and it seems to work really well. However, I agree with the above comments though that super detailed documentation will be helpful and that it's a bit hard to test with random data sets. All buttons/drop down menus/text boxes/check boxes/etc. seem to work on both desktop and mobile browsers.

**Comment by jimsafley** [comment]
I've made a change that fixes the inconsistency between a resource's display title and its `dcterms:title` (949b441b02e7a7fd37a8429c41c9183c61778d24). Try it out.

I've also changed the "Resource query" form element from a text input to the new query element (9dc01690975ba0b527e56c46c72d9f545aa69f60). Try that out as well.

**Comment by katknow** [comment]
Both of those changes work nicely for me across browsers!

**Comment by sharonmleon** [comment]
I have a question about the ways that Data Cleaning might work with custom vocab or value suggest. Should those data type changes have any impact on what shows up in the audit? (Sorry I accidentally left this comment on DataVis the first time.)

**Comment by sharonmleon** [comment]
Also, am I correct that there is no way to locate null values and correct them?

**Comment by sharonmleon** [comment]
Works with the additional data types. This is so neat and ready to be released, I think.
